#pragma once

namespace SoundUtil
{
	/*	SOUND DATA를 출력 시 이용 하는 열거형 타입들
	/	
	/	SOUND DATA를 출력 하고 싶을 시 아래
	/	SOUNDDATA->PlaySound() 함수를 이용
	/	SOUND_DATA_TYPE, SOUND_DATA_PLAY_TYPE를 입력 후
	/	SOUND NUMBER를 입력 할 것	
	/	
	/
	/	SOUND를 추가 하고 싶을 시
	/	Database 폴더 내에 있는 shortSoundList.txt 파일을 수정할 것
	/	SoundList.txt 파일을 참고하여 원하는 사운드의
	/	
	/   1. " * " 이 붙은 카테고리를 추가
	/   2. " - " 가 붙은 항목을 추가
	/	3. " = " 이 붙은 파일 이름을 추가
	/	4. cSoundData.cpp 파일에서 findSoundKey() 함수내에 추가 한
	/	사운드 파일의 최종 경로의 폴더 이름 soundKey로 추가
	/	
	*/

	enum SOUND_DATA_TYPE
	{
		SOUND_TYPE_MENU,				//타이틀 메뉴 SOUND
		SOUND_TYPE_BGM,					//게임 BGM SOUND
		SOUND_TYPE_PLAYER_EFFECT,		//플레이어 EFFECT SOUND
		SOUND_TYPE_PLAYER_VOICE,		//플레이어 VOICE SOUND
		SOUND_TYPE_NPC,					//NPC EFFECT SOUND
		SOUND_TYPE_STRUCT_BASEMENT,		//건물 실내 SOUND - 1
		SOUND_TYPE_STRUCT_FEMALEWARD,	//건물 실내 SOUND - 2
		SOUND_TYPE_ETC,					//기타
	};

	enum SOUND_DATA_PLAY_TYPE
	{
		//MENU SOUND
		SOUND_PLAY_TYPE_MENUBGM,					//MENU BGM								//SOUND_TYPE_MENU
		SOUND_PLAY_TYPE_MENUEFFECT,					//MENU EFFECT							//SOUND_TYPE_MENU

		//GAME BGM
		SOUND_PLAY_GAME_BGM,						//GAME BGM								//SOUND_TYPE_BGM

		//CHARACTER SOUND(PLAYER)
		SOUND_PLAY_TYPE_PLAYER_WALKING_NORMAL,		//PLAYER WALKING - 일반					//SOUND_TYPE_PLAYER_EFFECT
		SOUND_PLAY_TYPE_PLAYER_WALKING_WOOD,		//PLAYER WALKING - 나무					//SOUND_TYPE_PLAYER_EFFECT
		SOUND_PLAY_TYPE_PLAYER_WALKING_IRON,		//PLAYER WALKING - 철판					//SOUND_TYPE_PLAYER_EFFECT
		SOUND_PLAY_TYPE_PLAYER_WALKING_SOIL,		//PLAYER WALKING - 흙					//SOUND_TYPE_PLAYER_EFFECT

		SOUND_PLAY_TYPE_PLAYER_ATTACKED,			//PLAYER 피격							//SOUND_TYPE_PLAYER_VOICE
		SOUND_PLAY_TYPE_PLAYER_ATTACKED_RELAX,		//PLAYER 피격 후 진정되는 소리			//SOUND_TYPE_PLAYER_VOICE
		SOUND_PLAY_TYPE_PLAYER_ROPE,				//PLAYER 로프 소리						//SOUND_TYPE_PLAYER_VOICE

		SOUND_PLAY_TYPE_PLAYER_BREATH_ROUGH,		//PLAYER 거친 호흡 소리					//SOUND_TYPE_PLAYER_VOICE
		SOUND_PLAY_TYPE_PLAYER_DAED,				//PLAYER 죽을 때 소리					//SOUND_TYPE_PLAYER_VOICE
		SOUND_PLAY_TYPE_PLAYER_FEAR,				//PLAYER 두려움에 떠는 소리				//SOUND_TYPE_PLAYER_VOICE
		SOUND_PLAY_TYPE_PLAYER_FEARHIGH,			//PLAYER 두려움에 떠는 소리(절정)			//SOUND_TYPE_PLAYER_VOICE
		SOUND_PLAY_TYPE_PLAYER_NERVOUS,				//PLAYER ??								//SOUND_TYPE_PLAYER_VOICE
		SOUND_PLAY_TYPE_PLAYER_PAIN,				//PLAYER 고통받을 때 소리					//SOUND_TYPE_PLAYER_VOICE
		SOUND_PLAY_TYPE_PLAYER_RELAX,				//PLAYER 긴장이 점점 풀리는 소리			//SOUND_TYPE_PLAYER_VOICE
		SOUND_PLAY_TYPE_PLAYER_SCRAG,				//PLAYER 목졸림 당할 때 소리				//SOUND_TYPE_PLAYER_VOICE
		SOUND_PLAY_TYPE_PLAYER_SURPRISE,			//PLAYER 깜짝 놀랬을 때 소리				//SOUND_TYPE_PLAYER_VOICE

		SOUND_PLAY_TYPE_PLAYER_TRY_USE_KEY,			//PLAYER 키 사용 할 때 소리				//SOUND_TYPE_PLAYER_EFFECT
		SOUND_PLAY_TYPE_PLAYER_TRY_OPEN_CABINET,	//PLAYER 캐비닛 열 때 소리				//SOUND_TYPE_PLAYER_EFFECT
		SOUND_PLAY_TYPE_PLAYER_TRY_TURN_VALVE,		//PLAYER 밸브 열 때 소리					//SOUND_TYPE_PLAYER_EFFECT
		SOUND_PLAY_TYPE_PLAYER_TRY_CLOSE_VALVE,		//PLAYER 밸브 잠굴 때 소리				//SOUND_TYPE_PLAYER_EFFECT
		SOUND_PLAY_TYPE_PLAYER_OPEN_TAPE,			//PLAYER 테이프 넣을 때 소리				//SOUND_TYPE_PLAYER_EFFECT
		SOUND_PLAY_TYPE_PLAYER_SEARCH_DESK,			//PLAYER 책상 뒤지는 소리					//SOUND_TYPE_PLAYER_EFFECT
		SOUND_PLAY_TYPE_PLAYER_TYPEKEYBOARD,		//PLAYER 키보드 치는 소리					//SOUND_TYPE_PLAYER_EFFECT

		//CAM EFFECT SOUND
		SOUND_PLAY_TYPE_CAM_EFFECT,					//캠코더 이펙트 소리						//SOUND_TYPE_PLAYER_EFFECT

		//CHARACTER_SOUND(NPC)
		SOUND_PLAY_TYPE_NPC_SCISSORS,				//NPC 가위 질 소리						//SOUND_TYPE_NPC
		SOUND_PLAY_TYPE_NPC_KNIFE,					//NPC 나이프로 뭔가를 써는 소리			//SOUND_TYPE_NPC

		SOUND_PLAY_TYPE_ATTACK,						//NPC 공격 시 소리						//SOUND_TYPE_NPC

		SOUND_PLAY_TYPE_NPC_WALKING_HEAVY,			//NPC 걷는 소리(묵직함)					//SOUND_TYPE_NPC
		SOUND_PLAY_TYPE_NPC_WALKING_NORMAL,			//NPC 걷는 소리(일반)						//SOUND_TYPE_NPC
		SOUND_PLAY_TYPE_NPC_WALKING_STAIR,			//NPC 걷는 소리(계단)						//SOUND_TYPE_NPC
		SOUND_PLAY_TYPE_NPC_WALKING_IRON,			//NPC 걷는 소리(철판)						//SOUND_TYPE_NPC
		SOUND_PLAY_TYPE_NPC_WALKING_WATER,			//NPC 걷는 소리(물)						//SOUND_TYPE_NPC

		SOUND_PLAY_TYPE_NPC_BREECHING,				//NPC 뭔가 부시고 들어가는 소리			//SOUND_TYPE_NPC
		SOUND_PLAY_TYPE_NPC_TRY_BREECHING,			//NPC 뭔가 부실려고 시도하는 소리			//SOUND_TYPE_NPC
		SOUND_PLAY_TYPE_NPC_CHAIN,					//NPC 사슬 소리							//SOUND_TYPE_NPC
		SOUND_PLAY_TYPE_NPC_CUTBODY,				//NPC 시체 짜르는 소리					//SOUND_TYPE_NPC

		SOUND_PLAY_TYPE_NPC_TRYOPEN_DOOR,			//NPC 문 열려고 시도하는 소리				//SOUND_TYPE_NPC
		SOUND_PLAY_TYPE_NPC_OPEN_DOOR,				//NPC 문 여는 소리						//SOUND_TYPE_NPC

		//ROOM EFFECT SOUND
		SOUND_PLAY_TYPE_ROOM_RUN_FAR,				//방안에 걷는 소리(멀리서 들리는 듯한)		//SOUND_TYPE_STRUCT_FEMALEWARD
		SOUND_PLAY_TYPE_ROOM_RUN_CLOSE,				//방안에 걷는 소리(가까이서 들리는 듯한)	//SOUND_TYPE_STRUCT_FEMALEWARD
		SOUND_PLAY_TYPE_ROOM_SHOWER,				//샤워 룸 소리							//SOUND_TYPE_STRUCT_FEMALEWARD
		
		//HALLWAY EFFECT SOUND
		SOUND_PLAY_TYPE_HALLWAYRUN_FAR,				//복도 걷는 소리(멀리)					//SOUND_TYPE_STRUCT_FEMALEWARD
		SOUND_PLAY_TYPE_HALLWAYRUN_CLOSE,			//복도 걷는 소리(가까이)					//SOUND_TYPE_STRUCT_FEMALEWARD

		//LOOK EVENT SOUND
		SOUND_PLAY_TYPE_LOOKEVENT,					//갑툭튀 귀신 나올 법한 소리들				//SOUND_TYPE_STRUCT_FEMALEWARD

		//THUNDER SOUND
		SOUND_PLAY_TYPE_THUNDER,					//천둥소리(실내 기준)						//SOUND_TYPE_STRUCT_FEMALEWARD

		//MOOD SOUND
		SOUND_PLAY_TYPE_MOOD_HALL,					//복도 또는 실내 분위기 소리(공포)			//SOUND_TYPE_STRUCT_FEMALEWARD
		SOUND_PLAY_TYPE_MOOD_ROOM,					//방안에 분위기 소리(공포)				//SOUND_TYPE_STRUCT_FEMALEWARD

		//OBJECT SOUND
		SOUND_PLAY_TYPE_BEND,						//뭔가 구부러지는 소리					//SOUND_TYPE_STRUCT_FEMALEWARD
		SOUND_PLAY_TYPE_MACHINE_01,					//기계 소리 - 1							//SOUND_TYPE_STRUCT_FEMALEWARD
		SOUND_PLAY_TYPE_MACHINE_02,					//기계 소리 - 2							//SOUND_TYPE_STRUCT_BASEMENT
		SOUND_PLAY_TYPE_ELECTRIC,					//전기 소리								//SOUND_TYPE_STRUCT_BASEMENT
		SOUND_PLAY_TYPE_ELECTRIC_NOICE,				//전기 소리(잡음)							//SOUND_TYPE_STRUCT_BASEMENT
		SOUND_PLAY_TYPE_SWITCH,						//스위치 누르는 소리						//SOUND_TYPE_STRUCT_BASEMENT
		SOUND_PLAY_TYPE_WATERFALL,					//물 떨어지는 소리						//없음(사용 불가)
		SOUND_PLAY_TYPE_CAN,						//깡통 굴러가는 소리						//SOUND_TYPE_STRUCT_FEMALEWARD
		SOUND_PLAY_TYPE_DOORCLOSE,					//문 닫는 소리							//SOUND_TYPE_STRUCT_FEMALEWARD
		SOUND_PLAY_TYPE_FALLOBJECT,					//뭔가 떨어지는 소리						//SOUND_TYPE_STRUCT_FEMALEWARD
		SOUND_PLAY_TYPE_HALLWAYRUN,					//뭔가 복도를 뛰어가는 소리				//SOUND_TYPE_STRUCT_FEMALEWARD
		SOUND_PLAY_TYPE_HALLWAY,					//복도에서 나는 소리(NPC 걷는 소리랑 겹침)	//SOUND_TYPE_STRUCT_FEMALEWARD
		SOUND_PLAY_TYPE_IRONEFFECT,					//철판 이펙트 소리들						//SOUND_TYPE_STRUCT_FEMALEWARD
		SOUND_PLAY_TYPE_ROPE,						//로프 소리들							//SOUND_TYPE_STRUCT_FEMALEWARD
		SOUND_PLAY_TYPE_ELEVATOR					//엘리베이터 소리들						//SOUND_TYPE_STRUCT_BASEMENT

	};
}