#pragma once

namespace SoundUtil
{
	enum SOUND_DATA_TYPE
	{
		SOUND_TYPE_MENU,
		SOUND_TYPE_BGM,
		SOUND_TYPE_PLAYER_EFFECT,
		SOUND_TYPE_PLAYER_VOICE,
		SOUND_TYPE_NPC,
		SOUND_TYPE_STRUCT_BASEMENT,
		SOUND_TYPE_STRUCT_FEMALEWARD,
		SOUND_TYPE_ETC,
	};

	enum SOUND_DATA_PLAY_TYPE
	{
		//MENU SOUND
		SOUND_PLAY_TYPE_MENUBGM,
		SOUND_PLAY_TYPE_MENUEFFECT,

		//GAME BGM
		SOUND_PLAY_GAME_BGM,

		//CHARACTER SOUND(PLAYER)
		SOUND_PLAY_TYPE_PLAYER_WALKING_NORMAL,
		SOUND_PLAY_TYPE_PLAYER_WALKING_WOOD,
		SOUND_PLAY_TYPE_PLAYER_WALKING_IRON,
		SOUND_PLAY_TYPE_PLAYER_WALKING_SOIL,

		SOUND_PLAY_TYPE_PLAYER_ATTACKED,
		SOUND_PLAY_TYPE_PLAYER_ATTACKED_RELAX,
		SOUND_PLAY_TYPE_PLAYER_ROPE,

		SOUND_PLAY_TYPE_PLAYER_BREATH_ROUGH,
		SOUND_PLAY_TYPE_PLAYER_DAED,
		SOUND_PLAY_TYPE_PLAYER_FEAR,
		SOUND_PLAY_TYPE_PLAYER_FEARHIGH,
		SOUND_PLAY_TYPE_PLAYER_NERVOUS,
		SOUND_PLAY_TYPE_PLAYER_PAIN,
		SOUND_PLAY_TYPE_PLAYER_RELAX,
		SOUND_PLAY_TYPE_PLAYER_SCRAG,
		SOUND_PLAY_TYPE_PLAYER_SURPRISE,

		SOUND_PLAY_TYPE_PLAYER_TRY_USE_KEY,
		SOUND_PLAY_TYPE_PLAYER_TRY_OPEN_CABINET,
		SOUND_PLAY_TYPE_PLAYER_TRY_TURN_VALVE,
		SOUND_PLAY_TYPE_PLAYER_TRY_CLOSE_VALVE,
		SOUND_PLAY_TYPE_PLAYER_OPEN_TAPE,
		SOUND_PLAY_TYPE_PLAYER_SEARCH_DESK,
		SOUND_PLAY_TYPE_PLAYER_TYPEKEYBOARD,

		//CAM EFFECT SOUND
		SOUND_PLAY_TYPE_CAM_EFFECT,

		//CHARACTER_SOUND(NPC)
		SOUND_PLAY_TYPE_NPC_SCISSORS,
		SOUND_PLAY_TYPE_NPC_KNIFE,

		SOUND_PLAY_TYPE_ATTACK,

		SOUND_PLAY_TYPE_NPC_WALKING_HEAVY,
		SOUND_PLAY_TYPE_NPC_WALKING_NORMAL,
		SOUND_PLAY_TYPE_NPC_WALKING_STAIR,
		SOUND_PLAY_TYPE_NPC_WALKING_IRON,
		SOUND_PLAY_TYPE_NPC_WALKING_WATER,

		SOUND_PLAY_TYPE_NPC_BREECHING,
		SOUND_PLAY_TYPE_NPC_TRY_BREECHING,
		SOUND_PLAY_TYPE_NPC_CHAIN,
		SOUND_PLAY_TYPE_NPC_CUTBODY,

		SOUND_PLAY_TYPE_NPC_TRYOPEN_DOOR,
		SOUND_PLAY_TYPE_NPC_OPEN_DOOR,

		//ROOM EFFECT SOUND
		SOUND_PLAY_TYPE_ROOM_RUN_FAR,
		SOUND_PLAY_TYPE_ROOM_RUN_CLOSE,
		SOUND_PLAY_TYPE_ROOM_SHOWER,
		
		//HALLWAY EFFECT SOUND
		SOUND_PLAY_TYPE_HALLWAYRUN_FAR,
		SOUND_PLAY_TYPE_HALLWAYRUN_CLOSE,

		//LOOK EVENT SOUND
		SOUND_PLAY_TYPE_LOOKEVENT,

		//THUNDER SOUND
		SOUND_PLAY_TYPE_THUNDER,

		//MOOD SOUND
		SOUND_PLAY_TYPE_MOOD_HALL,
		SOUND_PLAY_TYPE_MOOD_ROOM,

		//OBJECT SOUND
		SOUND_PLAY_TYPE_BEND,
		SOUND_PLAY_TYPE_MACHINE_01,
		SOUND_PLAY_TYPE_MACHINE_02,
		SOUND_PLAY_TYPE_ELECTRIC,
		SOUND_PLAY_TYPE_ELECTRIC_NOICE,
		SOUND_PLAY_TYPE_SWITCH,
		SOUND_PLAY_TYPE_WATERFALL,
		SOUND_PLAY_TYPE_CAN,
		SOUND_PLAY_TYPE_DOORCLOSE,
		SOUND_PLAY_TYPE_FALLOBJECT,
		SOUND_PLAY_TYPE_HALLWAYRUN,
		SOUND_PLAY_TYPE_HALLWAY,
		SOUND_PLAY_TYPE_IRONEFFECT,
		SOUND_PLAY_TYPE_ROPE,

	};
}